### ISSUE TITLE
Úkol č.2

### ISSUE THREAD

**Issue by HelenaHanackova** [HelenaHanackova/python_pro_data_science_2023_Pt2#1]
Ahoj,
zde je odkaz na 2. úkol: https://github.com/HelenaHanackova/python_pro_data_science_2/blob/main/ukol_02.ipynb.
Zdraví,
Helena

**Comment by vaclavcepelak** [comment]
Ahoj Heleno, dobrá práce! Moc se mi líbí přehlednost kódu a komentáře. Jinak není moc co komentovat, protože to máš správně :). Je tam jedna zásadnější věc - chybí ti tam StandardScaler. A zároveň to není chyba, protože v tomhle případě zrovna není potřeba - věděla bys proč?

Nechci tě tím už zatěžovat, úkol je splněn (zadáno do tabulky). V rámci sekce "rady do života" přidávám pár formálních věcí:
- Je dobré nemít v tom notebooku importy, které pak nepoužíváš. VS Code ti je barevně odliší.
- Máš tam 2 soubory, oba vypadají stejně. Tak ten druhý pro jistotu vymaž, ať to nemate.
- Pokud bys chtěla nasdílet, v čem byl problém s tím původním repozitářem, dej vědět. Můžu ti dát info, abys příště věděla. Ale vím, že už je to dlouho.

Přeju hodně štěstí v práci s daty a i jinak!

V.
